version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: domergy-proxy
    networks:
      - domergy-services
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    logging:
     driver: "json-file"
     options:
      max-size: "1m"
      max-file: "3"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: domergy-certbot
    networks:
      - domergy-services
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
     driver: "json-file"
     options:
       max-size: "1m"
       max-file: "3"

networks:
  domergy-services:
    driver: "bridge"

